# Generated by Django 3.0.3 on 2020-02-19 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kennywoodapi', '0002_auto_20200219_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kennywoodapi.Attraction'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kennywoodapi.Customer'),
        ),
    ]
